# Site settings
title: Diseño de Sistemas
email: dds-jv-cursada@googlegroups.com
description: >- # this means to ignore newlines until "baseurl:"
  Conocé más sobre ésta temática
baseurl: ""
url: "https://dds-jv.github.io"

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jemoji

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
