plugins:
  - github-pages
  - jemoji

# Site settings
title: "Diseño de Sistemas"
description: "Conocé más sobre ésta temática"
email: dds-jv-cursada@googlegroups.com

# Blog cover
cover: /assets/images/cover.jpg
pagecover: /assets/images/pagecover.jpg
error: /assets/images/error.jpg

permalink: pretty

url: "http://dds-jv.github.io"
baseurl: ""